import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../core/constants/app_theme.dart';

/// Displays the complete list of automated speed violation incidents for the logged-in driver.
/// These records are auto-generated by LocationService when the speed threshold is exceeded.
class SpeedViolationHistoryScreen extends StatelessWidget {
  final String driverId;

  const SpeedViolationHistoryScreen({super.key, required this.driverId});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text("Speed Violation History", style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w800)),
        centerTitle: true,
      ),
      body: StreamBuilder<List<Map<String, dynamic>>>(
        // Query only rows that match the automated speeding violation pattern 
        stream: Supabase.instance.client
            .from('incidents')
            .stream(primaryKey: ['id'])
            .order('created_at', ascending: false),
        builder: (context, snapshot) {
          if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());
          if (snapshot.hasError) return Center(child: Text("Error loading violations: ${snapshot.error}"));

          // Filter client-side: only incidents with "Speeding Violation" in the title and matching driver ID
          final List<Map<String, dynamic>> violations = snapshot.data!.where((incident) {
            final title = incident['title']?.toString() ?? '';
            final note = incident['note']?.toString() ?? '';
            return title.contains('Speeding') || note.contains('Driver ID: $driverId');
          }).toList();

          if (violations.isEmpty) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.check_circle_outline, size: 72, color: AppTheme.primaryGreen.withOpacity(0.5)),
                  const SizedBox(height: 16),
                  const Text("No speed violations recorded!", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                  const SizedBox(height: 8),
                  const Text("Keep it up — drive safely inside the park", style: TextStyle(color: AppTheme.greyText)),
                ],
              ),
            );
          }

          return ListView.builder(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 40),
            itemCount: violations.length,
            itemBuilder: (context, index) {
              final v = violations[index];
              final date = v['created_at']?.toString().substring(0, 16) ?? 'Unknown';

              return Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: Container(
                  decoration: BoxDecoration(
                    color: Colors.red.withOpacity(0.05),
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: Colors.red.withOpacity(0.2)),
                  ),
                  child: ListTile(
                    leading: const CircleAvatar(
                      backgroundColor: Colors.red,
                      radius: 22,
                      child: Icon(Icons.speed, color: Colors.white, size: 22),
                    ),
                    title: Text(
                      v['title'] ?? 'Speeding Violation',
                      style: const TextStyle(fontWeight: FontWeight.w700, color: Colors.red),
                    ),
                    subtitle: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 4),
                        Text(v['note'] ?? '', style: const TextStyle(fontSize: 12, color: AppTheme.greyText)),
                        const SizedBox(height: 2),
                        Text("📅 $date", style: const TextStyle(fontSize: 12, color: AppTheme.greyText)),
                      ],
                    ),
                    isThreeLine: true,
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
